-- Vehicle dispatch management module (PC customer-service board).
-- The existing project uses bigint service_staff/vehicles IDs behind db-proxy,
-- so these tables intentionally follow the current schema instead of UUIDs.

ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS type_seq integer,
  ADD COLUMN IF NOT EXISTS "operator" text;

COMMENT ON COLUMN public.vehicles.type_seq IS 'Dispatch board fixed order within the same vehicle_model_short.';
COMMENT ON COLUMN public.vehicles."operator" IS 'Read-only dispatch display of operating company plus owner/person.';

CREATE TABLE IF NOT EXISTS public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES public.service_staff(id),
  CONSTRAINT customers_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT customers_name_key UNIQUE (name)
);

COMMENT ON TABLE public.customers IS '客户/货主主数据：派遣录入时自动沉淀，后续 CRM 可直接扩展。';

CREATE TABLE IF NOT EXISTS public.dispatch_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id bigint NOT NULL REFERENCES public.vehicles(id),
  dispatch_date date NOT NULL,
  customer_id bigint NOT NULL REFERENCES public.customers(id),
  agent_id bigint NOT NULL REFERENCES public.service_staff(id),
  is_substitute_driver boolean NOT NULL DEFAULT false,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.dispatch_records IS '车辆派遣记录：一条记录等于某车某日被某客户使用，由某客服录入。';
COMMENT ON COLUMN public.dispatch_records.agent_id IS '经手客服固定为录入人，后续管理员修改/删除不改变该字段。';
COMMENT ON COLUMN public.dispatch_records.is_substitute_driver IS '代驾标记，仅记录是否代驾，不记录具体人员。';
COMMENT ON COLUMN public.dispatch_records.is_deleted IS '软删除标记；硬删除不用于业务删除。';

CREATE TABLE IF NOT EXISTS public.dispatch_operation_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id bigint NOT NULL REFERENCES public.dispatch_records(id),
  action text NOT NULL,
  operator_id bigint NOT NULL REFERENCES public.service_staff(id),
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dispatch_operation_logs_action_check CHECK (action = ANY (ARRAY['create', 'update', 'delete']))
);

COMMENT ON TABLE public.dispatch_operation_logs IS '派遣记录操作日志：记录创建、修改、软删的操作人和变更快照。';

CREATE INDEX IF NOT EXISTS idx_customers_name_trgm
  ON public.customers USING gin (name public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_dispatch_records_month_vehicle
  ON public.dispatch_records (dispatch_date, vehicle_id)
  WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS idx_dispatch_records_vehicle_date
  ON public.dispatch_records (vehicle_id, dispatch_date)
  WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS idx_dispatch_records_agent
  ON public.dispatch_records (agent_id);

CREATE INDEX IF NOT EXISTS idx_dispatch_records_customer
  ON public.dispatch_records (customer_id);

CREATE INDEX IF NOT EXISTS idx_dispatch_operation_logs_record
  ON public.dispatch_operation_logs (record_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.prevent_dispatch_agent_change()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO ''
AS $$
BEGIN
  NEW.agent_id = OLD.agent_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_dispatch_records_updated_at ON public.dispatch_records;
CREATE TRIGGER set_dispatch_records_updated_at
  BEFORE UPDATE ON public.dispatch_records
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS prevent_dispatch_agent_change ON public.dispatch_records;
CREATE TRIGGER prevent_dispatch_agent_change
  BEFORE UPDATE ON public.dispatch_records
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_dispatch_agent_change();

CREATE OR REPLACE VIEW public.vehicles_sorted AS
 SELECT v.id,
    v.plate_number,
    v.vehicle_type,
    v.source,
    v.is_active,
    v.created_at,
    v.terminal_phone,
    v.fleet_name,
    v.group_number,
    v.group_leader,
    v.asset_owner,
    v.vehicle_model_short,
    v.vehicle_category,
    v.operating_company_id,
    v.brand,
    v.model,
    v.vin,
    v.engine_number,
    v.registration_date,
    v.license_issue_date,
    v.archive_number,
    v.approved_passengers,
    v.total_mass_kg,
    v.curb_mass_kg,
    v.load_mass_kg,
    v.traction_mass_kg,
    v.dimensions,
    v.scrap_date,
    v.inspection_expiry,
    v.barcode,
    v.insurance_expiry,
    v.filing_expiry,
    v.data_source,
        CASE v.data_source
            WHEN 'verified'::text THEN 1
            WHEN 'manual'::text THEN 2
            WHEN 'legacy'::text THEN 3
            ELSE 9
    END AS data_source_rank,
    oc.name AS operating_company_name,
    oc.short_name AS operating_company_short_name,
    v.type_seq,
    v."operator"
   FROM public.vehicles v
     LEFT JOIN public.operating_companies oc ON oc.id = v.operating_company_id;

COMMENT ON VIEW public.vehicles_sorted IS '车头列表视图：按 verified→manual→legacy 排序，并联表带出营运公司名';

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispatch_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispatch_operation_logs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.current_staff_id_from_jwt()
RETURNS bigint
LANGUAGE sql
STABLE
SET search_path TO ''
AS $$
  SELECT NULLIF(auth.jwt() -> 'app_metadata' ->> 'staff_id', '')::bigint;
$$;

CREATE OR REPLACE FUNCTION public.current_staff_role_from_jwt()
RETURNS text
LANGUAGE sql
STABLE
SET search_path TO ''
AS $$
  SELECT COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '');
$$;

DROP POLICY IF EXISTS customers_select_authenticated ON public.customers;
CREATE POLICY customers_select_authenticated
  ON public.customers
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS customers_insert_authenticated ON public.customers;
CREATE POLICY customers_insert_authenticated
  ON public.customers
  FOR INSERT
  TO authenticated
  WITH CHECK (created_by = public.current_staff_id_from_jwt());

DROP POLICY IF EXISTS dispatch_records_select_authenticated ON public.dispatch_records;
CREATE POLICY dispatch_records_select_authenticated
  ON public.dispatch_records
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS dispatch_records_insert_own ON public.dispatch_records;
CREATE POLICY dispatch_records_insert_own
  ON public.dispatch_records
  FOR INSERT
  TO authenticated
  WITH CHECK (agent_id = public.current_staff_id_from_jwt());

DROP POLICY IF EXISTS dispatch_records_update_own_or_admin ON public.dispatch_records;
CREATE POLICY dispatch_records_update_own_or_admin
  ON public.dispatch_records
  FOR UPDATE
  TO authenticated
  USING (
    public.current_staff_role_from_jwt() = 'admin'
    OR agent_id = public.current_staff_id_from_jwt()
  )
  WITH CHECK (
    public.current_staff_role_from_jwt() = 'admin'
    OR agent_id = public.current_staff_id_from_jwt()
  );

DROP POLICY IF EXISTS dispatch_operation_logs_select_own_or_admin ON public.dispatch_operation_logs;
CREATE POLICY dispatch_operation_logs_select_own_or_admin
  ON public.dispatch_operation_logs
  FOR SELECT
  TO authenticated
  USING (
    public.current_staff_role_from_jwt() = 'admin'
    OR operator_id = public.current_staff_id_from_jwt()
  );

DROP POLICY IF EXISTS dispatch_operation_logs_insert_own ON public.dispatch_operation_logs;
CREATE POLICY dispatch_operation_logs_insert_own
  ON public.dispatch_operation_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (operator_id = public.current_staff_id_from_jwt());

GRANT SELECT, INSERT, UPDATE ON public.customers TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.dispatch_records TO authenticated;
GRANT SELECT, INSERT ON public.dispatch_operation_logs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.customers_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.dispatch_records_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.dispatch_operation_logs_id_seq TO authenticated;

GRANT ALL ON TABLE public.customers TO service_role;
GRANT ALL ON TABLE public.dispatch_records TO service_role;
GRANT ALL ON TABLE public.dispatch_operation_logs TO service_role;
GRANT ALL ON SEQUENCE public.customers_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.dispatch_records_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.dispatch_operation_logs_id_seq TO service_role;
GRANT ALL ON FUNCTION public.prevent_dispatch_agent_change() TO service_role;
GRANT ALL ON FUNCTION public.current_staff_id_from_jwt() TO service_role;
GRANT ALL ON FUNCTION public.current_staff_role_from_jwt() TO service_role;
